#pragma once

// ─── TFLite Model Flatbuffer ──────────────────────────────────────────────────
// This file is generated by:   python training/train_model.py
//
// Steps to deploy a trained model:
//   1. Collect labelled data (see training/README in train_model.py header)
//   2. Run:  cd training && pip install -r requirements.txt && python train_model.py
//   3. The script writes  training/output/model_data.h  — copy it here.
//   4. Set MODEL_LOADED to 1 below.
//
// Until a trained model is available, the firmware uses the heuristic scoring
// path in inference.cpp which still provides useful AQS + RDR estimates.
// ─────────────────────────────────────────────────────────────────────────────

#ifndef MODEL_LOADED
#define MODEL_LOADED 0
#endif

#if MODEL_LOADED
// ── Paste generated model bytes here ─────────────────────────────────────────
// Example (replace with actual output from train_model.py):
//
// alignas(8) const unsigned char model_data[] = {
//     0x1c, 0x00, 0x00, 0x00, 0x54, 0x46, 0x4c, 0x33, ...
// };
// const unsigned int model_data_len = sizeof(model_data);

alignas(8) extern const unsigned char model_data[];
extern const unsigned int model_data_len;
#endif
